on:
  push:
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2  # Check out the repository code
  
        - name: Set up Docker buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to Amazon ECR
          id: login-ecr
          run: |
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com
        - name: Build Docker Image
          run: |
            docker build-t my-flask-app
        - name: Tag Docker image
          run: |
            docker tag my-flask-app ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/autopipelinerepo:latest

        - name: Push Docker image to Amazon ECR
          run: |
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/autopipelinerepo:latest

        - name: Set up AWS CLI
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2

            
          
 
 
          
          
         
